# Generated by Django 4.1 on 2023-05-02 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("PriceDashBoard", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="MatrialsModel",
            new_name="MaterialsModel",
        ),
        migrations.RenameModel(
            old_name="MatrialsPriceModel",
            new_name="MaterialsPriceModel",
        ),
        migrations.RenameField(
            model_name="materialsmodel",
            old_name="matrial_name",
            new_name="material_name",
        ),
        migrations.RenameField(
            model_name="materialspricemodel",
            old_name="matrial_id",
            new_name="material_name",
        ),
    ]
